version: '3.8'
services:
  movie_frontend_service:
    container_name: movie_frontend_service
    build: ./
    ports:
      - '${FRONTEND_CLIENT_PORT}:3000'
    env_file:
      - ./.env
    stdin_open: true # -i input flag
    tty: true # -t terminal flag
